spring:
  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres
    username: postgres.rdbhaslnimuynbfjkmlq
    password: GS2zG#Nc38aW##J
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: inter
  mail:
    host: smtp.gmail.com
    port: 587
    username: k1fernandesyt@gmail.com
    password: gxwczlmwrkmdptyx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

